#- name: add label to host
#  shell: "{{ lookup('template', 'ceph_orch_host_label_add.sh.j2') }}"

- name: deploy mon
  template:
    src: ceph_orch_apply_mon.sh.sh.j2
    dest: /tmp/ceph_orch_apply_mon.sh