---
- name: create /etc/systemd/resolved.conf.d/
  file:
    state: directory
    path: /etc/systemd/resolved.conf.d/

- name: copy dns config to server
  template:
    src: dns_servers.conf.j2
    dest: /etc/systemd/resolved.conf.d/dns_servers.conf
    mode: '0644'

- name: update network 
  systemd_service:
    name: systemd-resolved
    state: restarted
