---
# tasks file for ansible_openstack_ceph
- include_tasks: common.yml
- include_tasks: docker.yml
- name: reset ssh connection (newgrp docker equivalent)
  meta: reset_connection
- name: copy docker images
  include_tasks: docker_image.yml
- include_tasks: sshd.yml
  when: install_ceph|bool == true
- include_tasks: netplan.yml
  when: install_ceph|bool == true
- include_tasks: cephadm.yml
  when: install_ceph|bool == true and inventory_hostname in groups['deployer']
- include_tasks: ceph.yml
  when: install_ceph|bool == true and inventory_hostname in groups['deployer']
- include_tasks: ceph_mon.yml
  when: install_ceph|bool == true and inventory_hostname in groups['deployer']
- include_tasks: ceph_osd.yml
  when: install_ceph|bool == true and inventory_hostname in groups['deployer']
- include_tasks: ceph_pool_keyring.yml
  when: install_ceph|bool == true and inventory_hostname in groups['deployer']
- include_tasks: openstack_requirements.yml
  when: inventory_hostname in groups['deployer']
- include_tasks: openstack_preinstall.yml
  when: inventory_hostname in groups['deployer']
- include_tasks: openstack_install.yml
  when: inventory_hostname in groups['deployer']
