---
# tasks file for ansible_openstack_ceph
- include_tasks: common.yml
#- include_tasks: docker.yml
#- name: reset ssh connection
#  meta: reset_connection
#- name: copy docker images
#  include_tasks: docker_image.yml
- include_tasks: sshd.yml
- include_tasks: netplan.yml
- include_tasks: openstack_requirements.yml
  when: inventory_hostname in groups['deployer']
- include_tasks: openstack_preinstall.yml
  when: inventory_hostname in groups['deployer']
- include_tasks: openstack_install.yml
  when: inventory_hostname in groups['deployer']