---
- name: make kolla script runner
  template: 
    src: kolla-ansible.sh.j2
    dest: /tmp/kolla-ansible.sh

- name: kolla bootstrap-servers  
  shell: "/bin/bash /tmp/kolla-ansible.sh bootstrap-servers"

- name: kolla prechecks
  shell: "/bin/bash /tmp/kolla-ansible.sh prechecks"

#- name: kolla deploy
#  shell: "/bin/bash /tmp/kolla-ansible.sh deploy"
#
#- name: kolla post-deploy
#  shell: "/bin/bash /tmp/kolla-ansible.sh post-deploy"
