---
- name: make kolla script runner
  template: 
    src: kolla-ansible.sh.j2
    dest: /tmp/kolla-ansible.sh

- name: kolla bootstrap-servers  
  shell: "/bin/bash /tmp/kolla-ansible.sh bootstrap-servers"
  register: bootstrap_output

- name: bootstrap_output
  copy:
    content: "{{ bootstrap_output.stdout }}"
    dest: /tmp/bootstrap_output.txt
  delegate_to: localhost

- name: kolla prechecks
  shell: "/bin/bash /tmp/kolla-ansible.sh prechecks"
  register: prechecks_output

- name: prechecks_output
  copy:
    content: "{{ prechecks_output.stdout }}"
    dest: /tmp/prechecks_output.txt
  delegate_to: localhost

#- name: kolla deploy
#  shell: "/bin/bash /tmp/kolla-ansible.sh deploy"
#  register: deploy_output
#
#- name: deploy_output
#  copy:
#    content: "{{ deploy_output.stdout }}"
#    dest: /tmp/deploy_output.txt
#  delegate_to: localhost
#
#- name: kolla post-deploy
#  shell: "/bin/bash /tmp/kolla-ansible.sh post-deploy"
#  register: postdeploy_output
#
#- name: postdeploy_output
#  copy:
#    content: "{{ postdeploy_output.stdout }}"
#    dest: /tmp/postdeploy_output.txt
#  delegate_to: localhost