---
- name: install requirement packages for kolla-ansible
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-dev
    - libffi-dev
    - gcc
    - libssl-dev
    - python3-selinux
    - python3-setuptools
    - python3-venv
    - crudini
    - python3-openstackclient

- name: create venv for kolla
  shell: "mkdir -p {{kolla_directory}}"

- name: copy kolla-venv
  unarchive:
    src: kolla-ansible.tar
    dest: /opt/kolla
    owner: root
    group: root

- name: copy ansible collections for kolla
  unarchive:
    src: ansible_collections.tar
    dest: /root/
    owner: root
    group: root
    mode: '0755'
