- name: install requirement packages for kolla-ansible
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-dev
    - libffi-dev
    - gcc
    - libssl-dev
    - python3-selinux
    - python3-setuptools
    - python3-venv

- name: create venv for kolla
  shell: |
    mkdir -p {{kolla_directory}}
    python3 -m venv {{kolla_directory}}/kolla-venv

- name: installing kolla-ansible
  shell: |
    source {{kolla_directory}}/kolla-venv/bin/activate
    pip install -U pip 
    pip install 'ansible-core>=2.14,<=2.16'
    pip install git+https://opendev.org/openstack/kolla-ansible@stable/2023.1
    kolla-ansible install-deps
    mkdir -p {{kolla_config}}
    cp -r {{kolla_directory}}/kolla-venv/share/kolla-ansible/etc_examples/kolla/* {{kolla_config}}
    cp {{kolla_directory}}/kolla-venv/share/kolla-ansible/ansible/inventory/multinode {{kolla_config}}
