- name: install requirement packages for kolla-ansible
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-dev
    - libffi-dev
    - gcc
    - libssl-dev
    - python3-selinux
    - python3-setuptools
    - python3-venv
    - crudini

- name: create venv for kolla
  shell: "mkdir -p {{kolla_directory}} && cd {{kolla_directory}} && python3 -m venv {{kolla_venv}}"

- name: installing kolla-ansible
  shell: |
    . {{kolla_directory}}/{{kolla_venv}}/bin/activate
    {{kolla_directory}}/{{kolla_venv}}/bin/pip install -U pip 
    {{kolla_directory}}/{{kolla_venv}}/bin/pip install 'ansible-core>=2.14,<=2.16'
    {{kolla_directory}}/{{kolla_venv}}/bin/pip install git+https://opendev.org/openstack/kolla-ansible@stable/{{kolla_version}}
    {{kolla_directory}}/{{kolla_venv}}/bin/kolla-ansible install-deps
    mkdir -p {{kolla_config}}
    cp -r {{kolla_directory}}/kolla-venv/share/kolla-ansible/etc_examples/kolla/* {{kolla_config}}
    cp {{kolla_directory}}/kolla-venv/share/kolla-ansible/ansible/inventory/multinode {{kolla_config}}

#- name: copy multinode_edit script to server
#  copy:
#    src: files/clear_multinode.sh
#    dest: /tmp/clear_multinode.sh
#    mode: '0755'
#
#- name: clear multinode 
#  shell: /bin/bash /tmp/clear_multinode.sh
#
#- name: update multinode 
#  shell: "{{ lookup('template', 'openstack_multinode.sh.j2') }}"
#
#- name: edit globals.yml
#  template:
#    src: globals.yml.j2
#    dest: "{{ kolla_config }}/globals.yml"
#  
#- name: kolla-genpwd
#  shell: "{{kolla_directory}}/{{kolla_venv}}/bin/kolla-genpwd"
#
#- name: ceph.conf and keyring for openstack
#  file:
#    path: "{{ kolla_config }}/{{ item }}"
#    state: directory
#  with_items:
#    - "config"
#    - "config/nova"
#    - "config/glance"
#    - "config/cinder"
#    - "config/cinder/cinder-volume"
#    - "config/cinder/cinder-backup"
#
#- name: copying and editing keyring for ceph
#  shell: |
#    cp /etc/ceph/ceph.conf {{ kolla_config }}/config/cinder/
#    cp /etc/ceph/ceph.conf {{ kolla_config }}/config/nova/
#    cp /etc/ceph/ceph.conf {{ kolla_config }}/config/glance/
#    cp /etc/ceph/ceph.client.glance.keyring {{ kolla_config }}/config/glance/
#    cp /etc/ceph/ceph.client.nova.keyring {{ kolla_config }}/config/nova/
#    cp /etc/ceph/ceph.client.cinder.keyring {{ kolla_config }}/config/nova/
#    cp /etc/ceph/ceph.client.cinder.keyring {{ kolla_config }}/config/cinder/cinder-volume/
#    cp /etc/ceph/ceph.client.cinder.keyring {{ kolla_config }}/config/cinder/cinder-backup/
#    cp /etc/ceph/ceph.client.cinder-backup.keyring {{ kolla_config }}/config/cinder/cinder-backup/
#    find {{ kolla_config }}/config/ -type f | xargs sed -i $'s/\t//g'
#
#- name: kolla bootstrap-servers  
#  shell: ". {{kolla_directory}}/{{kolla_venv}}/bin/active && {{kolla_directory}}/{{kolla_venv}}/bin/kolla-ansible -i {{ kolla_config }}/multinode bootstrap-servers"
#
#- name: kolla prechecks
#  shell: ". {{kolla_directory}}/{{kolla_venv}}/bin/active && {{kolla_directory}}/{{kolla_venv}}/bin/kolla-ansible -i {{ kolla_config }}/multinode prechecks"
#
#- name: kolla deploy
#  shell: ". {{kolla_directory}}/{{kolla_venv}}/bin/active && {{kolla_directory}}/{{kolla_venv}}/bin/kolla-ansible -i {{ kolla_config }}/multinode deploy"
#
#- name: kolla post-deploy
#  shell: ". {{kolla_directory}}/{{kolla_venv}}/bin/active && {{kolla_directory}}/{{kolla_venv}}/bin/kolla-ansible -i {{ kolla_config }}/multinode post-deploy"
