---
- name: PermitRootLogin from first host
  when: inventory_hostname in groups['other_hosts']
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match Address {{ hostvars["openstack1"].ansible_host }}
              PermitRootLogin yes

- name: restart sshd
  systemd:
    name: sshd
    state: restarted
