---
- name: PermitRootLogin from first host
  when: inventory_hostname in groups['non_deployer']
  blockinfile:
    path: /etc/ssh/sshd_config
    state: present
    block: |
      {% for node in groups['deployer'] %}
      Match Address {{ hostvars[node].ansible_host }}
              PermitRootLogin yes

      {% endfor %}

- name: restart sshd
  systemd:
    name: sshd
    state: restarted
